name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Build artifact (${{ matrix.goos }}/${{ matrix.goarch }})
        run: |
          echo "Building artifact for ${{ matrix.goos }}/${{ matrix.goarch }}..."
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          BINARY_NAME="idled-${GOOS}-${GOARCH}"
          go build -o "./bin/${BINARY_NAME}" ./cmd/idled
        env:
          CGO_ENABLED: 0

      - name: Upload artifact (${{ matrix.goos }}/${{ matrix.goarch }})
        uses: actions/upload-artifact@v4
        with:
          name: idled-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bin/idled-${{ matrix.goos }}-${{ matrix.goarch }}

  publish-release:
    needs: release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List downloaded artifacts
        run: ls -R dist

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          name: idled ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*/*
          body: |
            ## Installation
            
            Download the command line tool from the release page or use the following command:
              
            ```bash
            curl -L https://github.com/younsl/idled/releases/download/${{ github.ref_name }}/idled-${{ matrix.goos }}-${{ matrix.goarch }} -o idled
            chmod +x idled
            ./idled --version
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}